version: '3.8'

services:
  financial-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - DATABASE_URL=sqlite:///financial_tracker.db
    volumes:
      # Persistent storage for database and logs
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.financial-tracker.rule=Host(`financial-tracker.localhost`)"
      - "traefik.http.routers.financial-tracker.entrypoints=web"

  # Optional: Add Redis for production caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - production

  # Optional: Add nginx for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - financial-tracker
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis_data:

# Development override
---
version: '3.8'

services:
  financial-tracker-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - SECRET_KEY=dev-secret-key
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["python", "app.py"]
    restart: unless-stopped
